### ISSUE TITLE
Compatibility with JSON-RPC spec

### ISSUE THREAD

**Issue by bbkr** [seban/ruby-getresponse#37]
On November 30th we introduced Notifications and Batches to GetResponse.

A Notification is a request without "id" member. Lack of this member means that the Request is a Notification - signifies the Clients lack of interest in receiving Response as explained [here](http://www.jsonrpc.org/specification#notification).

Since request is missing this param
https://github.com/seban/ruby-getresponse/blob/master/lib/get_response/connection.rb#L80
it will call Notification by mistake resulting in HTTP `204 No content` response.

**Comment by seban** [comment]
@bbkr I didn't have valid api key right now, so I cant check everything tight now.

**Comment by seban** [comment]
Closed with issue #38. Kudos to @kammerer
