### ISSUE TITLE
Existing Contact

### ISSUE THREAD

**Issue by mmaruri** [seban/ruby-getresponse#40]
How do you get a handle on one existing contact?  I see how you can grab all of them but what if you just want one?

**Comment by mmaruri** [comment]
Never mind - I found it.

**Comment by guiltry** [comment]
Hi, how you do it ?

**Comment by guiltry** [comment]
Found it.

http://rubydoc.info/gems/getresponse/0.6/GetResponse/Connection:send_request

But, how to receive it as a Contact class ?
Use ContactProxy instead.

gr_connection = GetResponse::Connection.new(api_key)
cproxy = GetResponse::ContactProxy.new(gr_connection)
contacts = cproxy.all("email" => {'EQUALS' => "example@example.com"})
